# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f72b094e53f8d4addc331b9357032cc81532c662c2e869c00f9f6519905d8a2399255d2408c4fd81c9b478b421b9edfd21f03d2714b95abbf7d5a1c475647d86

test:
  secret_key_base: 4e5eb5fa384f43cad7672d2c22ebe2a2dc0d2b7910a476823a37fb81bdda8d29550724dd856109be557cf5d935253b69a17afcff0f0a2d0c301a754e38fc2f75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
